name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: actions/metrics.plugin.steam.svg
          token: NOT_NEEDED
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "76561198977272054"
          plugin_steam_sections: player,recently-played
          plugin_steam_recent_games_limit: 3
          plugin_steam_achievements_limit: 0
      - uses: lowlighter/metrics@latest
        with:
          filename: actions/metrics.plugin.introduction.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: mogumc
          base: header
          plugin_introduction: yes
      - uses: lowlighter/metrics@latest
        with:
          filename: actions/metrics.plugin.traffic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_traffic: yes
      - uses: lowlighter/metrics@latest
        with:
          filename: actions/metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create         
      - uses: lowlighter/metrics@latest
        with:
          filename: actions/metrics.plugin.pagespeed.index.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://www.moguq.top
      - uses: lowlighter/metrics@latest
        with:
          filename: actions/metrics.plugin.pagespeed.blog.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://blog.moguq.top          
