name: Compress images
on: 
  push:
    branches: ["master", "main"]
    paths:
      - '**/**.jpg'
      - '**/**.jpeg'
      - '**/**.png'
      - '**/**.webp'
jobs:
  build:
    name: calibreapp/image-actions
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.METRICS_TOKEN }}
          ignorePaths: "actions/**,templates/**"
